"""init: create tables

Revision ID: 2950295a86a3
Revises: 
Create Date: 2026-05-05 21:08:06.138438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2950295a86a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('noti_enabled', sa.Boolean(), nullable=False),
    sa.Column('dark_mode', sa.String(), nullable=False),
    sa.Column('flood_weight', sa.SmallInteger(), nullable=False),
    sa.Column('security_weight', sa.SmallInteger(), nullable=False),
    sa.Column('noise_weight', sa.SmallInteger(), nullable=False),
    sa.Column('medical_weight', sa.SmallInteger(), nullable=False),
    sa.Column('congestion_weight', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("dark_mode IN ('SYSTEM', 'DARK', 'LIGHT')", name='users_dark_mode_check'),
    sa.CheckConstraint("user_type IN ('Single', 'Newlyweds', 'Dependents')", name='users_user_type_check'),
    sa.CheckConstraint('flood_weight + security_weight + noise_weight + medical_weight + congestion_weight = 100', name='users_weights_sum_check'),
    sa.CheckConstraint('flood_weight BETWEEN 0 AND 100 AND security_weight BETWEEN 0 AND 100 AND noise_weight BETWEEN 0 AND 100 AND medical_weight BETWEEN 0 AND 100 AND congestion_weight BETWEEN 0 AND 100', name='users_weights_range_check'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('provider', 'provider_id', name='users_provider_unique')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('address_detail', sa.String(), nullable=True),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('criminal_occur', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('cctv_count', sa.Integer(), nullable=False),
    sa.Column('lamp_count', sa.Integer(), nullable=False),
    sa.Column('police_dist', sa.Float(), nullable=False),
    sa.Column('safety_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('flood_hist', sa.Integer(), nullable=False),
    sa.Column('low_ratio', sa.SmallInteger(), nullable=False),
    sa.Column('pump_cap', sa.SmallInteger(), nullable=False),
    sa.Column('river_dist', sa.Integer(), nullable=False),
    sa.Column('flood_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('road_noise', sa.SmallInteger(), nullable=False),
    sa.Column('noise_report', sa.Integer(), nullable=False),
    sa.Column('ent_place', sa.Integer(), nullable=False),
    sa.Column('train_noise', sa.Integer(), nullable=False),
    sa.Column('noise_table', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medic_dist', sa.Integer(), nullable=False),
    sa.Column('nightopen_count', sa.Integer(), nullable=False),
    sa.Column('emeropen_count', sa.Integer(), nullable=False),
    sa.Column('emer_cap', sa.Integer(), nullable=False),
    sa.Column('doctor_ratio', sa.Float(), nullable=False),
    sa.Column('medic_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('congestion_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('security_score', sa.SmallInteger(), nullable=True),
    sa.Column('flood_score', sa.SmallInteger(), nullable=True),
    sa.Column('noise_score', sa.SmallInteger(), nullable=True),
    sa.Column('medical_score', sa.SmallInteger(), nullable=True),
    sa.Column('congestion_score', sa.SmallInteger(), nullable=True),
    sa.Column('total_score', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(security_score IS NULL OR security_score BETWEEN 0 AND 100) AND (flood_score IS NULL OR flood_score BETWEEN 0 AND 100) AND (noise_score IS NULL OR noise_score BETWEEN 0 AND 100) AND (medical_score IS NULL OR medical_score BETWEEN 0 AND 100) AND (congestion_score IS NULL OR congestion_score BETWEEN 0 AND 100) AND (total_score IS NULL OR total_score BETWEEN 0 AND 100)', name='reports_score_range_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_reports_region_code', 'reports', ['region_code'], unique=False)
    op.create_index('idx_reports_user_created_at', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('bookmark_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id'),
    sa.UniqueConstraint('user_id', 'report_id', name='bookmarks_unique_user_report')
    )
    op.create_index('idx_bookmarks_report_id', 'bookmarks', ['report_id'], unique=False)
    op.create_index('idx_bookmarks_user_id', 'bookmarks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookmarks_user_id', table_name='bookmarks')
    op.drop_index('idx_bookmarks_report_id', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index('idx_reports_user_id', table_name='reports')
    op.drop_index('idx_reports_user_created_at', table_name='reports')
    op.drop_index('idx_reports_region_code', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
