"""update report columns based on preprocessed data


"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '65588f32ed90'
down_revision: Union[str, Sequence[str], None] = '9c1f7a4e2b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ref_cctv_growth_gu_name_key'), 'ref_cctv_growth', type_='unique')
    op.drop_constraint(op.f('ref_crime_gu_name_key'), 'ref_crime', type_='unique')
    op.drop_constraint(op.f('ref_floating_pop_dong_code_key'), 'ref_floating_pop', type_='unique')
    op.drop_constraint(op.f('ref_health_workforce_gu_name_key'), 'ref_health_workforce', type_='unique')
    op.drop_constraint(op.f('ref_impervious_gu_name_key'), 'ref_impervious', type_='unique')
    op.drop_constraint(op.f('ref_noise_complaint_gu_name_key'), 'ref_noise_complaint', type_='unique')
    op.drop_constraint(op.f('ref_subway_congestion_station_name_key'), 'ref_subway_congestion', type_='unique')
    op.add_column('reports', sa.Column('cctv_growth', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('crime_count', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('safepath_score', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('police_count', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('police_pop_ratio', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('light_blind_ratio', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('impervious_ratio', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('noise_pub_density', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('noise_complaint', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('noise_db', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('aircraft_noise', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('rail_noise', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('noise_hourly', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('night_clinic', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('pharmacy_count', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('reports', sa.Column('medical_staff', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.alter_column('reports', 'cctv_count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('reports', 'altitude')
    op.drop_column('reports', 'ent_place')
    op.drop_column('reports', 'lamp_count')
    op.drop_column('reports', 'nightopen_count')
    op.drop_column('reports', 'flood_hist')
    op.drop_column('reports', 'medic_dist')
    op.drop_column('reports', 'police_dist')
    op.drop_column('reports', 'criminal_occur')
    op.drop_column('reports', 'low_ratio')
    op.drop_column('reports', 'train_noise')
    op.drop_column('reports', 'emer_cap')
    op.drop_column('reports', 'noise_report')
    op.drop_column('reports', 'doctor_ratio')
    op.drop_column('reports', 'river_dist')
    op.drop_column('reports', 'emeropen_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('emeropen_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('river_dist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('doctor_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('noise_report', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('emer_cap', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('train_noise', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('low_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('criminal_occur', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text("'{}'::integer[]"), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('police_dist', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('medic_dist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('flood_hist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('nightopen_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('lamp_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('ent_place', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('altitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('reports', 'cctv_count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('reports', 'medical_staff')
    op.drop_column('reports', 'pharmacy_count')
    op.drop_column('reports', 'night_clinic')
    op.drop_column('reports', 'noise_hourly')
    op.drop_column('reports', 'rail_noise')
    op.drop_column('reports', 'aircraft_noise')
    op.drop_column('reports', 'noise_db')
    op.drop_column('reports', 'noise_complaint')
    op.drop_column('reports', 'noise_pub_density')
    op.drop_column('reports', 'impervious_ratio')
    op.drop_column('reports', 'light_blind_ratio')
    op.drop_column('reports', 'police_pop_ratio')
    op.drop_column('reports', 'police_count')
    op.drop_column('reports', 'safepath_score')
    op.drop_column('reports', 'crime_count')
    op.drop_column('reports', 'cctv_growth')
    # ### end Alembic commands ###
